### ISSUE TITLE
Diseño de prototipo de aplicación adobe XD

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/diseno-de-prototipo-en-adobe-xd-o-figma-mitte#2]

**Comment by antoniio** [comment]
[Uploading Practica Prototipo.pdf…]()

**Comment by antoniio** [comment]
[Practica Prototipo.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-prototipo-en-adobe-xd-o-figma-mitte/files/6359684/Practica.Prototipo.pdf)

**Comment by Nancy2050** [comment]
Bien, cumple con la rúbrica.
Puntaje=20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado, solo el prototipo deben mejorar donde se registran los datos del usuario
